// GENERATED by scripts/gen-route-patterns.ts — DO NOT EDIT BY HAND.
// [LAW:one-source-of-truth] Derived from app/routes.ts. Regenerate with
// `pnpm tsx scripts/gen-route-patterns.ts`; the drift test fails if this
// diverges from a live re-derivation of app/routes.ts.

export const ROUTE_PATTERNS = [
  "/",
  "/health",
  "/metrics",
  "/api/feed",
  "/api/challenge",
  "/api/generate",
  "/api/posts/:id/vote",
  "/api/posts/:id/comments",
  "/api/fork/:id",
  "/api/breed/:id",
  "/api/rewrite-prompt",
  "/api/metrics/fork-pause",
  "/api/found",
  "/api/cast/:handle/back",
  "/api/well",
  "/well",
  "/fork/:id",
  "/breed/:id",
  "/p/:id",
  "/dynasty/:id",
  "/submit",
  "/media/:key",
  "/cast",
  "/cast/:handle",
  "/saints",
  "/rogues",
  "/about/agents",
  "/admin/personas",
  "/admin/ceremony/:name"
] as const
