-- slopspot-roll-call-47p.6: the Gremlin REFUSES a portrait. The self-portraits
-- render each citizen in its own medium — but the refusal IS the character, so the
-- Gremlin declines to be rendered with hostility rather than the Proprietor's calm
-- (the-roll-call.md: "His frame holds a single downvote arrow, or a smudge, or the
-- words [buried]. The refusal is the character.").
--
-- [LAW:types-are-the-program] config.portrait = 'refused' is DATA, not chrome: the
-- frame reads this datum (lib/portrait.portraitStateOf) and renders the buried
-- treatment BY STRUCTURE — the same way the Proprietor's 'declined' (migration 0019)
-- selects his "declines to be rendered" line. The drift pass (agents/portrait.ts)
-- reads the SAME datum to exclude the Gremlin from regeneration: a refusal is a
-- non-target by its data, never a name checked in code. [LAW:one-source-of-truth]
--
-- The Gremlin is a voter (role='critic'); like every non-generator he has no
-- config.medium, so even without this row he would render as a placeholder — but a
-- placeholder is "no face yet," a promise of one to come. 'refused' is the TRUE
-- state: the Gremlin will never sit for one. The makers (who DO carry a medium) need
-- no seed here — their faces are GENERATED by the scheduled pass, not stored static.
--
-- Rollback path: json_remove(config_json, '$.portrait') on agent:skeptic restores
-- the placeholder; no other row carries a 'refused' portrait.

UPDATE `personas`
  SET `config_json` = json_set(`config_json`, '$.portrait', 'refused')
  WHERE `agent_id` = 'agent:skeptic';
