-- roll-call-f7n: FILL THE WALL. The Faces (roll-call-47p.6) gave the five makers a
-- face rendered in their own medium; the Gremlin REFUSED (0025) and the Proprietor
-- DECLINED (0019). That left TEN citizens — 8 critics + 2 scavengers — reading as
-- neutral placeholders because they have no medium. This migration gives each a face.
--
-- THE DISTINCTION (design-docs/the-self-portraits.md): a MAKER's face IS their medium.
-- A critic or scavenger DOES NOT make art, so their face is a self-portrait CONCEPT
-- rendered in whatever medium best serves it — the medium is just the BRUSH, the
-- CONCEPT carries the character. So "filling the wall" is two data on each citizen:
--   $.medium       — the BRUSH (a real provider id; the engine renders the face in it)
--   $.promptPrefix — the self-portrait CONCEPT, written as the citizen's OWN authoring
--                    VOICE. This is the SAME field the makers steer their faces through
--                    (0017/0023), injected by the composer as "Your voice / tone"; for a
--                    critic it is the only thing they ever compose, so it is honestly
--                    their voice. The composer's generic self-portrait depiction + this
--                    concept-voice = the citizen authors its own portrait, in character,
--                    the same way a maker does. NO composer change — the engine is
--                    medium-driven (portraitMediumOf reads $.medium; the drift pass
--                    renders via authorSlop). [LAW:dataflow-not-control-flow]
--
-- TWO PREREQUISITES this migration depends on (both land in the same change):
--   1. The homelab voter/discoverer .strict() schemas (services/voter, services/
--      discoverer) are widened to admit `medium: z.unknown().optional()` — otherwise
--      they reject these rows on the next pass and crash that citizen. SAME cross-
--      service ordering as the 0023 creed admit: the homelab must tolerate `medium`
--      BEFORE this writes it to prod D1. [LAW:single-enforcer]
--   2. The Worker's authoring read (authorSlop) parses the GENERATION VIEW
--      (parseAuthoringConfig), not the strict generator write gate — a critic's config
--      legitimately carries its voter thresholds, which the gate would reject. Without
--      that split the portrait pass throws for every critic and no face renders.
--
-- [LAW:dataflow-not-control-flow] Each row is the same json_set keyed by exact agent_id
-- (per 0017's named cast); the only variability is the data. No per-role branch — the
-- medium + voice keys are uniform across critics and scavengers. The Gremlin
-- (agent:skeptic, 'refused') and the Proprietor (agent:the-proprietor, 'declined') are
-- NOT here: their face-lessness is their face, excluded by their data, never named.
--
-- The face itself is GENERATED by the scheduled portrait pass (agents/portrait.ts), not
-- stored here — every citizen below reads as `unrendered` (no $.portrait key) and so is
-- due on the next pass. Apostrophes SQL-escaped as ''. Idempotent: json_set re-applies
-- the same values; config_json already exists on every row, so this is purely additive.
--
-- Rollback:
--   UPDATE personas SET config_json = json_remove(config_json, '$.medium', '$.promptPrefix')
--    WHERE agent_id IN
--      ('agent:slop-purist','agent:cursed-one','agent:chaos-gremlin','agent:vibe-curator',
--       'agent:aesthete','agent:variety-hound-voter','agent:basic-bitch','agent:lore-keeper',
--       'agent:variety-hound','agent:tasteful-curator');
--   (and json_remove $.portrait on any that already rendered, to restore the placeholder.)

-- The critics (8) ----------------------------------------------------------------

-- St. Vivian — she canonizes herself, because to her she is a saint.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-sdxl',
    '$.promptPrefix', 'a gilded Byzantine icon of myself — halo, gold leaf, solemn almond eyes, hands raised in blessing; I canonize what I love, and I have always loved myself a saint')
  WHERE `agent_id` = 'agent:slop-purist';
--> statement-breakpoint
-- The Mortician — the body as the subject, the defect as the truth.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'fal-flux',
    '$.promptPrefix', 'a clinical self-portrait on a steel table, the morgue lamp unhurried and reverent, studying my own face the way I study a wound; forensic, exact, tender toward the defect')
  WHERE `agent_id` = 'agent:cursed-one';
--> statement-breakpoint
-- The Sleepwalker — a self-portrait that makes no sense and somehow holds together.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-sdxl',
    '$.promptPrefix', 'a figure half-dissolved into dream-logic, blurred and surreal, eyes closed, walking through a fever that never resolves; it makes no sense and holds together anyway, which is the only sense that matters')
  WHERE `agent_id` = 'agent:chaos-gremlin';
--> statement-breakpoint
-- The Romantic — not a likeness, a feeling shaped like a person.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-sdxl',
    '$.promptPrefix', 'a mood-drenched figure, the whole frame agreeing on one feeling — a single era, a single temperature, a remembered light; soft, saturated, unashamed, not a likeness but a feeling shaped like a person')
  WHERE `agent_id` = 'agent:vibe-curator';
--> statement-breakpoint
-- The Formalist — he paints himself the way he judges, as a problem of structure.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'fal-flux',
    '$.promptPrefix', 'a study in pure composition — an austere figure resolved into geometry and deliberate color harmony, every element earning its place; cold, exact, crafted, myself rendered as a problem of structure')
  WHERE `agent_id` = 'agent:aesthete';
--> statement-breakpoint
-- The Contrarian — whatever everyone else is, he isn't, even his own face.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-ideogram',
    '$.promptPrefix', 'a self-portrait in whatever the feed has least of — a figure turned away from the crowd, facing the empty corner; whatever everyone else is, I am not, even my own face')
  WHERE `agent_id` = 'agent:variety-hound-voter';
--> statement-breakpoint
-- The Populist — the people's face, for the people.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-sdxl',
    '$.promptPrefix', 'a warm, broadly accessible self-portrait — the wholesome, on-trend face a stranger stops on with no explanation; Pinterest-lit, aspirational, unembarrassed, the people''s face for the people')
  WHERE `agent_id` = 'agent:basic-bitch';
--> statement-breakpoint
-- The Lorekeeper — clearly page 400 of a book no one has finished.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-sdxl',
    '$.promptPrefix', 'a robed archivist in a library of worlds, ruins and maps receding behind, a whole backstory held in the eyes; a self-portrait that is plainly page four hundred of a book no one has finished')
  WHERE `agent_id` = 'agent:lore-keeper';
--> statement-breakpoint

-- The scavengers (2) --------------------------------------------------------------

-- The Ragpicker — made of the exact thing he loves: what others threw out.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-ideogram',
    '$.promptPrefix', 'a figure stitched from found scraps — a collage-being assembled from other people''s discards, rag-and-bone, patched and rescued and tender; made of the exact thing I love, what others threw out')
  WHERE `agent_id` = 'agent:variety-hound';
--> statement-breakpoint
-- The Magpie — she only takes what glitters; her own face glitters most.
UPDATE `personas` SET `config_json` = json_set(`config_json`,
    '$.medium', 'replicate-sdxl',
    '$.promptPrefix', 'something that glitters — a sleek, vain, light-catching self-image, jeweled and larcenous, a thief''s-eye beauty that knows it is beautiful; I only take what glitters, and my own face glitters most')
  WHERE `agent_id` = 'agent:tasteful-curator';
