// [LAW:one-source-of-truth] Generator for app/lib/route-patterns.generated.ts.
// Reads the SAME route table the app serves (app/routes.ts) and emits the flat
// pattern list as a committed constant the CPU tail worker imports without pulling
// the @react-router/dev build dependency into its bundle. The drift test
// (app/lib/__tests__/route-canonicalize.test.ts) re-derives from app/routes.ts and
// asserts equality, so the constant cannot silently fall out of sync.
//
// Run: pnpm tsx scripts/gen-route-patterns.ts

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import routes from '../app/routes'
import { flattenRoutePatterns } from '../app/lib/route-canonicalize'

const patterns = flattenRoutePatterns(routes)

const out = `// GENERATED by scripts/gen-route-patterns.ts — DO NOT EDIT BY HAND.
// [LAW:one-source-of-truth] Derived from app/routes.ts. Regenerate with
// \`pnpm tsx scripts/gen-route-patterns.ts\`; the drift test fails if this
// diverges from a live re-derivation of app/routes.ts.

export const ROUTE_PATTERNS = ${JSON.stringify(patterns, null, 2)} as const
`

const target = fileURLToPath(
  new URL('../app/lib/route-patterns.generated.ts', import.meta.url),
)
writeFileSync(target, out)
console.log(`wrote ${patterns.length} patterns to ${target}`)
